In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import shapefile
import os
import matplotlib as mpl
import matplotlib.pyplot as plt

import geopandas as gpd
import folium
from folium.plugins import FastMarkerCluster

# a nice way of filtering out deprecated warnings
import warnings
warnings.filterwarnings("ignore")
os.chdir("../raw_data/")

In [4]:
data_files = ["march_taxi.csv","april_taxi.csv","may_taxi.csv","june_taxi.csv","july_taxi.csv","august_taxi.csv",
         "september_taxi.csv", "october_taxi.csv", 
         "november_taxi.csv","december_taxi.csv"]
combined_csv = pd.concat([pd.read_csv(file) for file in data_files])

In [5]:
combined_csv

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2020-03-01 00:31:13,2020-03-01 01:01:42,1.0,4.70,1.0,N,88,255,1.0,22.00,3.0,0.5,2.00,0.00,0.3,27.80,2.5
1,2.0,2020-03-01 00:08:22,2020-03-01 00:08:49,1.0,0.00,1.0,N,193,193,2.0,2.50,0.5,0.5,0.00,0.00,0.3,3.80,0.0
2,1.0,2020-03-01 00:52:18,2020-03-01 00:59:16,1.0,1.10,1.0,N,246,90,1.0,6.00,3.0,0.5,1.95,0.00,0.3,11.75,2.5
3,2.0,2020-03-01 00:47:53,2020-03-01 00:50:57,2.0,0.87,1.0,N,151,238,1.0,5.00,0.5,0.5,1.76,0.00,0.3,10.56,2.5
4,1.0,2020-03-01 00:43:19,2020-03-01 00:58:27,0.0,4.40,1.0,N,79,261,1.0,16.50,3.0,0.5,4.05,0.00,0.3,24.35,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1461892,NaN,2020-12-31 23:44:35,2021-01-01 00:01:22,NaN,9.22,NaN,NaN,143,20,NaN,32.49,0.0,0.5,8.16,0.00,0.3,43.95,2.5
1461893,NaN,2020-12-31 23:41:36,2020-12-31 23:50:32,NaN,4.79,NaN,NaN,4,262,NaN,13.22,0.0,0.5,3.65,0.00,0.3,20.17,2.5
1461894,NaN,2020-12-31 23:01:17,2020-12-31 23:40:37,NaN,28.00,NaN,NaN,210,78,NaN,69.31,0.0,0.5,2.75,6.12,0.3,78.98,0.0
1461895,NaN,2020-12-31 23:31:29,2020-12-31 23:44:22,NaN,7.08,NaN,NaN,148,129,NaN,35.95,0.0,0.5,2.75,0.00,0.3,39.50,0.0
1461896,NaN,2020-12-31 23:12:48,2020-12-31 23:24:51,NaN,2.35,NaN,NaN,18,235,NaN,17.09,0.0,0.5,2.75,0.00,0.3,20.64,0.0